// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbc8STGmXufusw6ybAUiAxvAmi-9b2beY',
    appId: '1:444393064266:web:d7c3aa40bb9fb88b8963b3',
    messagingSenderId: '444393064266',
    projectId: 'ahmad-cd17f',
    authDomain: 'ahmad-cd17f.firebaseapp.com',
    storageBucket: 'ahmad-cd17f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWi_izb8eac3NuU6IRE4pNBn5poAyQ_o',
    appId: '1:444393064266:android:43a55da7afc2cfb58963b3',
    messagingSenderId: '444393064266',
    projectId: 'ahmad-cd17f',
    storageBucket: 'ahmad-cd17f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmUAblnSRSj0NhNWO2l82YfG0bel23dZw',
    appId: '1:444393064266:ios:6fc7d733c59704118963b3',
    messagingSenderId: '444393064266',
    projectId: 'ahmad-cd17f',
    storageBucket: 'ahmad-cd17f.appspot.com',
    iosClientId: '444393064266-8hqaaed0rdpvhfumgu71jju9ucpkc119.apps.googleusercontent.com',
    iosBundleId: 'com.example.ltuc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmUAblnSRSj0NhNWO2l82YfG0bel23dZw',
    appId: '1:444393064266:ios:6fc7d733c59704118963b3',
    messagingSenderId: '444393064266',
    projectId: 'ahmad-cd17f',
    storageBucket: 'ahmad-cd17f.appspot.com',
    iosClientId: '444393064266-8hqaaed0rdpvhfumgu71jju9ucpkc119.apps.googleusercontent.com',
    iosBundleId: 'com.example.ltuc',
  );
}
